#!/usr/bin/env python3
#
# This file is part of the Robotic Observatory Control Kit (rockit)
#
# rockit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rockit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rockit.  If not, see <http://www.gnu.org/licenses/>.

"""Commandline client for communicating with environmentd"""

# pylint: disable=bare-except

import datetime
import glob
import json
import os
import sys
import Pyro4
from rockit.common import TFmt
from rockit.environment import Config

SCRIPT_NAME = os.path.basename(sys.argv[0])
sys.excepthook = Pyro4.util.excepthook


SET_LABELS = {
    'BoolPowerOnOff': {
        False: TFmt.Bold + 'POWER OFF' + TFmt.Clear,
        True: TFmt.Bold + 'POWER ON' + TFmt.Clear
    },
    'BoolClosedOpen': {
        False: TFmt.Bold + 'OPEN' + TFmt.Clear,
        True: TFmt.Bold + 'CLOSED' + TFmt.Clear
    },
    'BoolSafeTripped': {
        False: TFmt.Bold + TFmt.Red + 'TRIPPED' + TFmt.Clear,
        True: TFmt.Bold + TFmt.Green + 'SAFE' + TFmt.Clear
    },
    'BoolHealthyUnhealthy': {
        False: TFmt.Bold + TFmt.Red + 'UNHEALTY' + TFmt.Clear,
        True: TFmt.Bold + TFmt.Green + 'HEALTHY' + TFmt.Clear
    },
    'UPSStatus': {
        1: TFmt.Bold + TFmt.Red + 'UNKNOWN' + TFmt.Clear,
        2: TFmt.Bold + TFmt.Green + 'ONLINE' + TFmt.Clear,
        3: TFmt.Bold + TFmt.Yellow + 'ON BATTERY' + TFmt.Clear,
        4: TFmt.Bold + TFmt.Red + 'SMART BOOST' + TFmt.Clear,
        5: TFmt.Bold + TFmt.Red + 'TIMED SLEEPING' + TFmt.Clear,
        6: TFmt.Bold + TFmt.Red + 'SOFTWARE BYPASS' + TFmt.Clear,
        7: TFmt.Bold + TFmt.Red + 'OFF' + TFmt.Clear,
        8: TFmt.Bold + TFmt.Red + 'REBOOTING' + TFmt.Clear,
        9: TFmt.Bold + TFmt.Red + 'SWITCHED BYPASS' + TFmt.Clear,
        10: TFmt.Bold + TFmt.Red + 'HARDWARE FAILURE BYPASS' + TFmt.Clear,
        11: TFmt.Bold + TFmt.Red + 'SLEEPING UNTIL POWER RETURNS' + TFmt.Clear,
        12: TFmt.Bold + TFmt.Red + 'ON SMART TRIM' + TFmt.Clear
    }
}


def print_status(daemon):
    """Prints the latest environment data in human-readable form"""
    try:
        with daemon.connect() as environment:
            data = environment.status()
    except Pyro4.errors.CommunicationError:
        print('error: unable to communicate with the environment daemon')
        return 1

    if data is None:
        print('No data available')
    else:
        # Find the longest label to set the parameter indent
        max_label_length = 0
        for watcher_data in data.values():
            for parameter_data in watcher_data['parameters'].values():
                max_label_length = max(max_label_length, len(parameter_data['label']))

        for watcher_data in data.values():
            print(watcher_data['label'] + ' data from ' + format_date(watcher_data['parameters']))
            for parameter_data in watcher_data['parameters'].values():
                label = parameter_data['label']
                label_padding = max_label_length - len(label)
                suffix = ''
                if 'unit' in parameter_data:
                    suffix = ' ' + parameter_data['unit']

                output = ' ' * label_padding + label + ': '
                if 'values' in parameter_data:
                    output += format_set(parameter_data)
                else:
                    output += format_measurement(parameter_data, suffix)

                print(output)
            print()

    return 0


def print_json(daemon):
    """Prints the latest environment data in machine-readable form"""
    try:
        with daemon.connect() as environment:
            status = environment.status()
    except Pyro4.errors.CommunicationError:
        print('error: unable to communicate with the environment daemon')
        return 1

    print(json.dumps(status))

    return 0


def format_date(data):
    """Builds a formatted date string for the named data group"""
    start = None
    end = None
    current = False
    for param in data.values():
        try:
            param_start = datetime.datetime.strptime(param['date_start'],
                                                     '%Y-%m-%dT%H:%M:%SZ')
            param_end = datetime.datetime.strptime(param['date_end'], '%Y-%m-%dT%H:%M:%SZ')
            start = param_start if not start else min(start, param_start)
            end = param_end if not end else min(end, param_end)
            current = current or param['current']
        except:
            pass

    ret = TFmt.Bold
    if start and end:
        ret += start.strftime('%H:%M:%S') + ' \u2014 '
        if not current:
            ret += TFmt.Red
        ret += end.strftime('%H:%M:%S') + TFmt.Clear
        ret += TFmt.Bold + ':' + TFmt.Clear
    else:
        ret += TFmt.Red + 'NO DATA' + TFmt.Clear
    return ret


def format_value(value, data, fmt='.1f'):
    """Builds a formatted string colored based on the specified limits"""
    color = TFmt.Bold
    limits = data.get('limits', None)
    warn_limits = data.get('warn_limits', None)

    if limits or warn_limits:
        if limits and (value < limits[0] or value > limits[1]):
            color += TFmt.Red
        elif warn_limits and (value < warn_limits[0] or value > warn_limits[1]):
            color += TFmt.Yellow
        else:
            color += TFmt.Green

    display = data.get('display', None)
    if display == 'DiskBytes':
        value = str(round(value / 2**30, 1))
        fmt = ''
    elif display in SET_LABELS:
        value = SET_LABELS[display].get(value, value)
        fmt = ''

    return color + ('{0' + fmt + '}').format(value) + TFmt.Clear


def format_measurement(data, suffix='', fmt='.1f'):
    """Builds a formatted string with a value range"""
    if fmt != '':
        fmt = ':' + fmt

    ret = ''
    if 'min' in data:
        ret += format_value(data['min'], data, fmt) + ' \u2264 '

    if data['current']:
        ret += format_value(data['latest'], data, fmt)
    else:
        ret += TFmt.Red + TFmt.Bold + 'NO DATA' + TFmt.Clear

    if 'max' in data:
        ret += ' \u2264 ' + format_value(data['max'], data, fmt)

    if data['current'] or 'max' in data:
        ret += suffix

    if data['unsafe']:
        ret += TFmt.Red + TFmt.Bold + ' (UNSAFE)' + TFmt.Clear
    elif data['warning']:
        ret += TFmt.Red + TFmt.Yellow + ' (WARNING)' + TFmt.Clear

    return ret


def format_set(data):
    """Builds a formatted string with specified values"""
    labels = []
    if 'display' in data:
        labels = SET_LABELS.get(data['display'], [])

    if data['current']:
        ret = labels.get(data['latest'], data['latest'])
    else:
        ret = TFmt.Red + TFmt.Bold + 'NO DATA' + TFmt.Clear

    if 'values' in data and (len(data['values']) > 1 or not data['current']):
        if ret:
            ret += ' '
        display_values = [labels.get(v, v) for v in data['values']]
        ret += '[' + ', '.join(display_values) + ']'

    if data['unsafe']:
        ret += TFmt.Red + TFmt.Bold + ' (UNSAFE)' + TFmt.Clear
    elif data['warning']:
        ret += TFmt.Red + TFmt.Yellow + ' (WARNING)' + TFmt.Clear

    return ret


def print_usage(name):
    """Prints the utility help"""
    print(f'Usage: {name} <command>')
    print()
    print('   status      print a human-readable summary of the aggregated environment status')
    print('   json        print a machine-readable summary of the aggregated environment status')
    print()

    return 1


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit(print_usage(SCRIPT_NAME))

    if 'ENVIRONMENTD_CONFIG_PATH' in os.environ:
        config = Config(os.environ['ENVIRONMENTD_CONFIG_PATH'])
    else:
        # Load the config file defined in the ENVIRONMENTD_CONFIG_PATH environment variable or from the
        # default system location (/etc/environmentd/). Exit with an error if zero or multiple are found.
        files = glob.glob("/etc/environmentd/*.json")
        if len(files) != 1:
            print('error: failed to guess the default config file. ' +
                  'Run as ENVIRONMENTD_CONFIG_PATH=/path/to/config.json environment <command>')
            sys.exit(1)

        config = Config(files[0])

    if sys.argv[1] == 'status':
        sys.exit(print_status(config.daemon))
    elif sys.argv[1] == 'json':
        sys.exit(print_json(config.daemon))

    # Command not found
    sys.exit(print_usage(SCRIPT_NAME))
